import failurelab


EXPECTED_V1_PUBLIC_API = {
    "BatchExperiment",
    "BatchExperimentRunner",
    "BatchOutput",
    "BoundaryComparison",
    "CheckpointRisk",
    "ClassPolicy",
    "ClassPolicyEvaluation",
    "ClassPolicyViolation",
    "ConfiguredSuiteRunner",
    "CrossStressClassResult",
    "CrossStressPolicy",
    "CrossStressPolicyEvaluation",
    "CrossStressPolicyViolation",
    "CrossStressReport",
    "CustomStressTest",
    "EvaluationGateConfig",
    "EvaluationGateResult",
    "EvaluationGateStatus",
    "EvaluationHandler",
    "EvaluationHealth",
    "EvaluationHealthStatus",
    "EvaluationInputs",
    "EvaluationIntelligence",
    "EvaluationPlan",
    "EvaluationProfile",
    "EvaluationProfileValidation",
    "EvaluationReport",
    "EvaluationStepResult",
    "EvaluationSummary",
    "ExperimentOutput",
    "ExperimentRunner",
    "FailureBoundary",
    "FailureCluster",
    "FailureClusterPolicy",
    "FailureClusterPolicyEvaluation",
    "FailureClusterPolicyViolation",
    "FailureClusterReport",
    "FailureCorrelationPolicy",
    "FailureCorrelationPolicyEvaluation",
    "FailureCorrelationPolicyViolation",
    "FailureCorrelationReport",
    "FailureDiagnosis",
    "FailureDiagnosticReport",
    "FailureEnvelope",
    "FailureForecast",
    "FailureForecastPolicyResult",
    "FailureForecastReport",
    "FailureLab",
    "FailureLabReport",
    "FailureOccurrence",
    "FailurePersistence",
    "FailurePersistencePolicyResult",
    "FailurePersistenceReport",
    "FailurePriority",
    "FailurePrioritySignal",
    "FailureRecurrence",
    "FailureRemediation",
    "FailureResolution",
    "FailureResolutionPolicyResult",
    "FailureResolutionReport",
    "FailureSignature",
    "FailureSignatureComparison",
    "FailureSignatureType",
    "FailureTriageComparison",
    "FailureTriagePolicyResult",
    "FailureTriageReport",
    "ForecastStatus",
    "HistoryEntry",
    "LoadedClassPolicy",
    "ModelComparison",
    "PersistenceLevel",
    "PolicyEvaluation",
    "PolicyReport",
    "PolicyViolation",
    "PriorityLevel",
    "ProgressionHistoryReport",
    "ProgressionPoint",
    "ProgressionPolicyResult",
    "ProgressionReport",
    "ProgressionStatus",
    "ProgressionTrend",
    "ResolutionStatus",
    "RobustnessPolicy",
    "RobustnessRegressionError",
    "SampleFailurePolicy",
    "SampleFailurePolicyEvaluation",
    "SampleFailurePolicyViolation",
    "SampleFailureReport",
    "SampleFailureResult",
    "SavedStressResult",
    "SignatureCheckpoint",
    "SignatureComparisonStatus",
    "SignatureHistoryPolicyResult",
    "SignatureHistoryReport",
    "SignatureHistoryTrend",
    "SignaturePolicyResult",
    "StressCorrelationResult",
    "StressFailureSignal",
    "StressPolicy",
    "StressSpec",
    "SuiteConfig",
    "SuiteHistory",
    "SuiteResult",
    "TriageComparisonPolicyResult",
    "TriageComparisonStatus",
    "VALID_HEALTH_STATUSES",
    "analyze_cross_stress_classes",
    "analyze_failure_correlations",
    "analyze_failure_persistence",
    "analyze_failure_recurrence",
    "analyze_failure_resolution",
    "analyze_progression",
    "analyze_progression_history",
    "analyze_report_correlations",
    "analyze_sample_failures",
    "analyze_signature_history",
    "build_cross_stress_report",
    "build_evaluation_inputs",
    "build_evaluation_intelligence",
    "build_evaluation_plan",
    "build_evaluation_report",
    "build_evaluation_summary",
    "build_failure_cluster_report",
    "build_failure_clusters",
    "build_failure_correlation_report",
    "build_failure_diagnostic_report",
    "build_failure_forecast_report",
    "build_failure_persistence_report",
    "build_failure_remediations",
    "build_failure_resolution_report",
    "build_failure_signature",
    "build_failure_triage_report",
    "build_policy_report",
    "build_report_clusters",
    "build_sample_failure_report",
    "build_stress_tests",
    "calculate_failure_correlation",
    "calculate_priority_score",
    "classify_cross_stress_severity",
    "classify_evaluation_health",
    "classify_failure_signature",
    "classify_forecast_status",
    "classify_persistence",
    "classify_priority_level",
    "classify_progression",
    "classify_progression_trend",
    "classify_resolution_status",
    "classify_sample_failure_severity",
    "classify_signature_comparison",
    "classify_signature_history_trend",
    "compare_failure_signatures",
    "compare_failure_triage",
    "compare_reports",
    "diagnose_failure_signature",
    "diagnostic_report_to_dict",
    "evaluate_class_policy",
    "evaluate_cross_stress_policy",
    "evaluate_failure_cluster_policy",
    "evaluate_failure_correlation_policy",
    "evaluate_failure_forecast_policy",
    "evaluate_failure_persistence_policy",
    "evaluate_failure_resolution_policy",
    "evaluate_failure_triage_policy",
    "evaluate_intelligence_gate",
    "evaluate_policy",
    "evaluate_progression_policy",
    "evaluate_report_gate",
    "evaluate_sample_failure_policy",
    "evaluate_signature_history_policy",
    "evaluate_signature_policy",
    "evaluate_triage_comparison_policy",
    "evaluation_report_to_dict",
    "export_evaluation_json",
    "export_failure_forecast_json",
    "export_failure_persistence_json",
    "export_failure_resolution_json",
    "export_failure_triage_json",
    "export_progression_json",
    "export_signature_history_json",
    "export_signature_json",
    "export_triage_comparison_json",
    "failure_forecast_to_dict",
    "failure_persistence_to_dict",
    "failure_rate_delta",
    "failure_resolution_to_dict",
    "failure_signature_to_dict",
    "failure_triage_to_dict",
    "forecast_failure_trajectory",
    "highest_risk_checkpoint",
    "identify_primary_driver",
    "load_class_policy",
    "load_cross_stress_policy",
    "load_evaluation_gate_config",
    "load_evaluation_profile",
    "load_failure_cluster_policy",
    "load_failure_correlation_policy",
    "load_robustness_policy",
    "load_sample_failure_policy",
    "load_suite_config",
    "progression_report_to_dict",
    "rank_failure_priorities",
    "remediation_for_driver",
    "resolve_input_path",
    "run_evaluation",
    "run_evaluation_gate",
    "score_checkpoint_risk",
    "signature_comparison_to_dict",
    "signature_history_to_dict",
    "summarize_progression_history",
    "triage_comparison_to_dict",
    "validate_evaluation_profile",
}


def test_v1_public_api_exactly_matches_frozen_surface():
    assert set(
        failurelab.__all__
    ) == EXPECTED_V1_PUBLIC_API


def test_v1_public_api_symbol_count():
    assert len(
        failurelab.__all__
    ) == 211


def test_v1_public_api_has_no_duplicates():
    assert len(
        failurelab.__all__
    ) == len(
        set(
            failurelab.__all__
        )
    )


def test_v1_public_api_symbols_exist():
    missing = [
        name
        for name in EXPECTED_V1_PUBLIC_API
        if not hasattr(
            failurelab,
            name,
        )
    ]

    assert missing == []


def test_v1_public_api_does_not_expose_unexpected_names():
    unexpected = (
        set(
            failurelab.__all__
        )
        - EXPECTED_V1_PUBLIC_API
    )

    assert unexpected == set()